### ISSUE TITLE
[QLC 4.13.1] E1.31 channel data output is inoperable on MacOS Sequoia - local network privacy related

### ISSUE THREAD

**Issue by nkaminski** [mcallegari/qlcplus#1641]
**Describe the bug**
On macOS Sequoia 15.1.1, the E1.31 output module in QLC+ 4.13.1 fails to send data and continually reports zero packets sent even with configured with a valid unicast or multicast destination address.

**To Reproduce**
1. Open QLC+ 4.13.1 on MacOS Sequoia 15.1.1
2. Configure a unicast E1.31 output with a valid destination IP located in the same subnet as the mac.
3. Observe that no E1.31 packets are sent and that no traffic is received at the configured destination.

**Expected behavior**
E1.31 packets should be sent when the E1.31 output is configured with a valid destination address and enabled.

**Desktop (please complete the following information):**
 - OS: Mac OS Sequoia 15.1.1
 - QLC+ Version 4.13.1

**Additional context**
Almost certainly related to the local network privacy changes described at https://developer.apple.com/forums/thread/663858. Running QLC+ from the terminal by invoking `/Applications/QLC+.app/Contents/MacOS/qlcplus` works around the issue and restores normal behavior.

**Comment by yestalgia** [comment]
Hey thanks for the bug report, I was going to suggest that the Apple update has caused a problem but you've already mentioned it.

I think we may need to wait for them to come up with a fix, but thanks for the work around!

Is ArtNet output also inhibited by Apple's update to Sequoia 15.1.1?

Cheers,
Lachie

**Comment by nkaminski** [comment]
Yes, I believe you need to add the local network + multicast entitlement to
the macOS app bundle manifest.

I was thinking of potentially debugging this and preparing a PR sometime
before the end of November if others don't beat me to it.

Regards,
Nash

**Comment by mcallegari** [comment]
I pushed the required keys. Please check if it works as expected. Thanks

**Comment by nkaminski** [comment]
Will build and test this weekend. Thanks for addressing this @mcallegari !

**Comment by kelvinyap9** [comment]
Hi! FYI 4.14.1-1 is still not prompting for Local Network. I was spending hours and hours wondering why E1.31 wasn't working then realised it was due to this Privacy & Security permission. This is my first time using QLC+ so wasn't sure if I missed something.

There is no way to add the app manually in this list so the only method I can use for now is to run from Terminal which gives it full permissions. Thanks!

**Comment by enbyted** [comment]
4.14.3 - same issue

**Comment by mcallegari** [comment]
I'm sorry but at this point I am not capable of fixing this issue.
Apple is giving developers hard times and unclear instructions.

**Comment by yestalgia** [comment]
Should we add a warning for Mac OS users to the UI?

**Comment by simonseres** [comment]
This issue still persists.
Ran into it today. Opening the QLC+.app would prevent E1.31 from working.
However, starting the binary from terminal 
`./Applications/QLC+.app/Contents/MacOS/qlcplus`
works.
