### ISSUE TITLE
Needlessly architecture-specific build system

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [mcallegari/qlcplus#1644]
**Describe the bug**

The build system is needlessly architecture-specific: for example, all Unix platforms are assumed to be x86, and all Android platforms are assumed to be armv7. The main issue this causes is that the installation directory on Linux is always `/usr/lib/x86_64-linux-gnu`, which is not in the library path on non-x86 systems (like the Raspberry Pi).

**To Reproduce**

1. Build and install on Raspberry Pi (tested with 5 under the recommended official RPi OS image, others should behave similarly); build should succeed.
2. Program cannot be started because `/usr/bin/qlcplus: error while loading shared libraries: libqlcpluswebaccess.so: cannot open shared object file: No such file`. However, this file exists and was installed to its intended directory according to `make install`.

**Expected behavior**

As far as no architecture-specific code exists in QLC, everything should just build on aarch64, RISC-V, and other platforms.

**Comment by mcallegari** [comment]
Where are these references you're talking about?
Only appimage and coverage builds have hardcoded x86_64-linux-gnu paths.

**Comment by kleinesfilmroellchen** [comment]
> Where are these references you're talking about? Only appimage and coverage builds have hardcoded x86_64-linux-gnu paths.

These are in the install paths. As I say, the *build* succeeds without issues. For instance, to make a basic QLC+ work under Raspberry Pi 5, I quickly hacked:

```diff
diff --git a/variables.cmake b/variables.cmake
index 3a89857f8..6950ab16e 100644
--- a/variables.cmake
+++ b/variables.cmake
@@ -89,7 +89,7 @@ if (WIN32)
 elseif (APPLE)
     set(LIBSDIR "Frameworks")
 elseif (UNIX)
-    set(LIBSDIR "lib/x86_64-linux-gnu")
+    set(LIBSDIR "lib/aarch64-linux-gnu")
 endif ()

 if (ANDROID)
```

> If you're building with qmake or not following the wiki instructions then this report is invalid

As I should have said more clearly, I am building exactly according to the wiki instructions, using a different CMake path to account for the different Qt5 CMake file. I have tested this issue with both the Ninja and Make generators of CMake, so they do not play a role (I prefer to build with ninja but am aware that it causes issues sometimes; this is not one of them).

**Comment by mcallegari** [comment]
You're not building the latest sources
https://github.com/mcallegari/qlcplus/blob/master/variables.cmake#L92

This has been fixed months ago.

**Comment by kleinesfilmroellchen** [comment]
Then why is this not fixed on the last 5.0 beta? I prefer to build relatively stable tags instead of the main branch.

**Comment by mcallegari** [comment]
Check the dates
4.13.1 - May 31st 2024
5.0.0 beta3 - December 30th 2023

So how can a fix from November 2024 can be included in one of the above?

If you can't live without a one-line fix that you can apply to 4.13.1, then you need to wait for the next release.

**Comment by kleinesfilmroellchen** [comment]
Hm. I don't understand the release policy of QLC in comparison to other open-source projects. (And in either case, I don't even know with the branching setup whether it applies to the last 4.x patch release, I hope you have checked that)
