### ISSUE TITLE
A channel fade out can be interrupted

### ISSUE THREAD

**Issue by plugz** [mcallegari/qlcplus#786]
Example in the second attached workspace here:

http://qlcplus.org/forum/viewtopic.php?f=5&t=9427

"chase-submaster.qxw"

**Comment by mcallegari** [comment]
Is this fixed by d95a77ae9f2f68dd609cb93317999eac5c4ecd4d or is it something else ?

**Comment by plugz** [comment]
Not fixed yet.

I have to add details to this issue, it's not very clear right now...

**Comment by plugz** [comment]
details here:

http://qlcplus.org/forum/viewtopic.php?f=12&t=9687

**Comment by mcallegari** [comment]
Workspace here: http://pastebin.com/4icmnfrY

There a 3 scenes:
20s, 100ms, 0ms

The "20s" scene has a 20seconds fade out.
The "100ms" scene, a 100ms fade out.
The "0ms" scene, a 0ms fade out.

The 3 scenes act on the same channel.

Now, go to the virtual console, run scene "20s", and stop it. The channel will go down from 100% to 0%, very slowly.
If after 5 seconds, I start and stop the "100ms" or the "0ms" scene, the 20s fadeout will disappear: the channel will go up to 100%, then down to 0%, very quickly. Instantly in the case of the "0ms" scene.
-> The 20s timeout has disappeared.


Is this a normal behavior ? Should the "20s" timeout continue after the "100ms" timeout reaches the value where the 20s fadeout would be at this time ?
